services:
 php:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: php
  volumes:
    - ./src:/var/www/html
  ports:
   - "8080:80"
  depends_on:
   - mysql


 mysql:
  image: mysql:latest
  container_name: mysql
  environment:
   MYSQL_ROOT_PASSWORD: secret
   MYSQL_DATABASE: mydatabase
   MYSQL_USER: myuser
   MYSQL_PASSWORD: mypassword
  volumes:
   - mysql_data:/var/lib/mysql


volumes:
 mysql_data: